### ISSUE TITLE
Alternative triggers discussion

### ISSUE THREAD

**Issue by Facyla** [woodenbell/html-utils-package#1]
Hi, 

Nice small package - these are my 2 cents on it :) 

Using espanso globally, i encounter some unwanted text expansions triggered, which are usually triggered by ":a". As espanso intercepts this sequence even in a middle of a word, it happens when using a gmail filter which i write "label:a-faire"  (TODO label). This also happens when using search functions in text editors, especially when editing CSS, or language translations. 

I'm not sure this happens a lot for other users, however these are the tweaks i am experimenting to avoid this issue : 
- use " :" instead of ":" (with a leading space) : i like the way it doesn't really change the trigger, while mitigating the false replacement issue for several use cases. 
- use "::" instead of ":" : this is a more "explicit" method, but still very quick with doubling. I'm still wondering if it would match more or less false positive than the other option...

When using leading space, it may be useful to also add a leading space in the replacement text so the space actually remains after replacement.

Package users can update their settings file pretty easily using search/replace, or providing an alternative package with other triggers might be a nice option too. 

Sincerely

**Comment by woodenbell** [comment]
Hi,
I've decided to update the package, changing the prefix from `:` to `::` for all triggers, since typing an extra `:` won't take anyone's time. I've issued a request for the developer of espanso to update my package in the package repository. When it happens I'll close the issue. Thanks for using the package and thanks for your suggestions!

**Comment by woodenbell** [comment]
The package has been updated, so I'm closing this, thanks for your suggestions!
