### ISSUE TITLE
Tag requests

### ISSUE THREAD

**Issue by usizu** [woodenbell/html-utils-package#3]
It said on the page to suggest any tags we could need, the following came up for me:
::p for` <p></p>`
::ul for 
```
<ul>
  <li></li>
</ul>
```
::li for `<li></li>`
::a2 for `<a href="{{clipboard}}" target="_blank" rel="noopener noreferrer">$|$</a>` (mainly for the `target` and the `rel`).
Thanks for the great tool!

**Comment by woodenbell** [comment]
Solved in #5
